### 
GET http://[::1]:5173/api/demo-api
Content-Type: application/json

###
GET http://[::1]:5173/api/comments
Content-Type: application/json


### 
POST http://[::1]:5173/api/comments
Content-Type: application/json

{
  "text":"test sen data from client"
}

###
GET http://[::1]:5173/api/comments/10
Content-Type: application/json

###
PATCH http://[::1]:5173/api/comments/10
Content-Type: application/json

{
  "text":"text is updated"
}
